# feeder
feeder: feeder.Feeder
seed: 10
phase: 'train'
print_log: True
show_topk: [1]

# model
model_args:
  in_feature: 6 # 6, 18
  out_class: 8

# optim
optimizer: 'AdamW'
weight_decay: 0.0005
base_lr: 0.001
step: []

# training
num_epoch: 600
device: [0]
batch_size: 64
test_batch_size: 256
nesterov: True
start_epoch: 0
eval_start: 0





